apache:
    build: apache
    restart: always
    volumes:
        - /var/www:/var/www
    ports:
        - 8080:80
    links:
        - php:php
    environment:
        - VIRTUALHOST=local.dev

              
nginx:
    build: nginx
    restart: always
    volumes:
        - /var/www:/var/www
    ports:
        - 80:80
    links:
        - php:php

php:
    build: php-fpm
    restart: always
    volumes:
        - /var/www:/var/www
    ports:
        - 9000:9000
    links :
        - db:db

db:
    image: mysql
    restart: always
    volumes:
        - /var/mysql:/var/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root

dockerUi:
    image: dockerui/dockerui
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 5000:9000
